server:
  port: 8888
   
spring:
  application:
    name: ConfigServer
  # Cloud config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/didorg/ms-config
          clone-on-start: true
          #username: forPrivateGithubRepo
          #password: forPrivateGithubRepo
          search-paths:
           - restaurant
           - customer
